// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NarutoCharacters.API.DbContexts;

#nullable disable

namespace NarutoCharacters.API.Migrations
{
    [DbContext(typeof(NinjaContext))]
    [Migration("20231113020931_NarutoDBInitialMigration")]
    partial class NarutoDBInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("NarutoCharacters.API.Entities.Jutsu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NinjaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NinjaId");

                    b.ToTable("Jutsus");
                });

            modelBuilder.Entity("NarutoCharacters.API.Entities.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("NarutoCharacters.API.Entities.Jutsu", b =>
                {
                    b.HasOne("NarutoCharacters.API.Entities.Ninja", "Ninja")
                        .WithMany("Jutsus")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NarutoCharacters.API.Entities.Ninja", b =>
                {
                    b.Navigation("Jutsus");
                });
#pragma warning restore 612, 618
        }
    }
}
