// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NarutoCharacters.API.DbContexts;

#nullable disable

namespace NarutoCharacters.API.Migrations
{
    [DbContext(typeof(NinjaContext))]
    [Migration("20231113022137_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("NarutoCharacters.API.Entities.Jutsu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NinjaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NinjaId");

                    b.ToTable("Jutsus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A spinning ball of chakra formed and held in the palm of the user's hand.",
                            Name = "Rasengan",
                            NinjaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A jutsu that creates an identical copy of the user.",
                            Name = "Shadow Clone Jutsu",
                            NinjaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Enhances the user's physical abilities.",
                            Name = "Sage Mode",
                            NinjaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "A high concentration of lightning chakra in the user's hand.",
                            Name = "Chidori",
                            NinjaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "A special eye technique granting advanced visual capabilities.",
                            Name = "Sharingan",
                            NinjaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "A jutsu that heals injuries.",
                            Name = "Medical Ninjutsu",
                            NinjaId = 3
                        });
                });

            modelBuilder.Entity("NarutoCharacters.API.Entities.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The main protagonist of the series.",
                            Name = "Naruto Uzumaki"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Naruto's rival and a skilled ninja.",
                            Name = "Sasuke Uchiha"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A member of Team 7.",
                            Name = "Sakura Haruno"
                        });
                });

            modelBuilder.Entity("NarutoCharacters.API.Entities.Jutsu", b =>
                {
                    b.HasOne("NarutoCharacters.API.Entities.Ninja", "Ninja")
                        .WithMany("Jutsus")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NarutoCharacters.API.Entities.Ninja", b =>
                {
                    b.Navigation("Jutsus");
                });
#pragma warning restore 612, 618
        }
    }
}
